pkg: pine64: uboot-pinephone: build crust
dreemurrs-embedded/Pine64-Arch pull request #15
Opened 2020-07-16 18:52 UTC by flacks

2020-08-17 02:15 UTC, flacks commented
Sure, that works.

2021-07-20 07:44 UTC, DrRac27 requested changes
Does not compile.

2021-07-20 07:44 UTC, DrRac27 commented on PKGBUILDS/pine64/uboot-pinephone/PKGBUILD
> +        'https://musl.cc/or1k-linux-musl-cross.tgz'
```
$ file or1k-linux-musl-cross/bin/or1k-linux-musl-gcc
or1k-linux-musl-cross/bin/or1k-linux-musl-gcc: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped
```
Obviously this will not work on aarch64...

2021-07-20 07:44 UTC, DrRac27 commented on PKGBUILDS/pine64/uboot-pinephone/PKGBUILD
> +         '10dae56d99711b0459c1f6cf46797baf'
This source is not for a fixed version so this md5sum is outdated. `'SKIP'` would be an option but I would rather like to see the toolchain be built from source or pulled from the repo.

2021-07-20 07:44 UTC, DrRac27 commented on PKGBUILDS/pine64/uboot-pinephone/PKGBUILD
> +  msg2 "Building U-Boot for PineTab..."
To quote the [Arch Wiki](https://wiki.archlinux.org/title/Arch_package_guidelines#Package_etiquette):
> Do not use makepkg subroutines (e.g. error, msg, msg2, plain, warning) as they might change at any time. To print data, use printf or echo.

2021-07-20 07:44 UTC, DrRac27 commented on PKGBUILDS/pine64/uboot-pinephone/PKGBUILD
> +  CROSS_COMPILE=../or1k-linux-musl-cross/bin/or1k-linux-musl- make scp
We are already on aarch64 so we don't need to cross compile...

2022-09-18 13:47 UTC, closed without merging